global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'vllm'
    scheme: https
    static_configs:
      - targets: ['127.0.0.1:7654']
    metrics_path: /metrics 
    tls_config:
      insecure_skip_verify: true
  
  - job_name: 'cir3-app'
    static_configs:
      - targets: ['127.0.0.1:8000']
    metrics_path: /metrics
    scrape_interval: 10s
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9054']
    
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']